print("Hello, welcome to the Scale factor representation calclator. The purpose of this calculator is to represent scale factor change to make it more easy to understand for aspiring mathematicians.")
print("All representations will be done using a cube since due to its square nature it is very easy to scale and will perfectly represent all of the scaling with a lot of ease.")
sideLen = int(input("What is the length of one side of your cube?\n"))
print("One side of your cube is", sideLen**2, "units squared.")
print("The area of the cube is", sideLen**3, "units cubed.")
lenSF = int(input("What is the length scale factor?\n"))
print("Now one side of your cube is", (sideLen*lenSF)**2, "units squared.")
print("Now the area of your cube is", (sideLen*lenSF)**3, "units cubed.")
print("Now notice how the area of one side increased by a scale factor of", lenSF**2, "which is exactly the side length you inputted squared.")
print("Now notice how the volume of your cube increased by a scale factor of", lenSF**3, "which is exactly the side length you inputted cubed.")
print("Now notice how this goes both ways. For example, if the volume scale factor is 8 then the length scale factor will be 2 which is the cube root of 8 and the area scale factor was 4 which is the cube root of 8 squared(it is squared since this is what is done when we go from length scale factor to area scale factor)")
print("We hope you enjoyed!")
